# Generated by Django 4.2.5 on 2023-09-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
